
name: Docker Build Tag Push

description: Build, tag and push Docker image

inputs:
  docker_username:
    required: true
  docker_token:
    required: true
  image_name:
    required: true
  image_tag:
    required: true

runs:
  using: composite

  steps:
    - name: Login to Docker Hub
      shell: bash
      run: |
        echo "${{ inputs.docker_token }}" | docker login -u "${{ inputs.docker_username }}" --password-stdin

    - name: Build Image
      shell: bash
      run: |
        docker build -t ${{ inputs.image_name }}:${{ inputs.image_tag }} .

    - name: Tag Image
      shell: bash
      run: |
        docker tag ${{ inputs.image_name }}:${{ inputs.image_tag }} ${{ inputs.docker_username }}/${{ inputs.image_name }}:${{ inputs.image_tag }}

    - name: Push Image
      shell: bash
      run: |
        docker push ${{ inputs.docker_username }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
